//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppConsola.ServiciosConsola {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosConsolaSoap", Namespace="http://tempuri.org/")]
    public partial class ServiciosConsola : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidarUsuarioConsolaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerParametrosConfiguracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarParametrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearEditarModeradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerInfoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarModeradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearEditarSectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerInfoSectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarSectorOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearEditarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerInfoCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarHashOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosConsola() {
            this.Url = global::AppConsola.Properties.Settings.Default.AppConsola_ServiciosConsola_ServiciosConsola;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidarUsuarioConsolaCompletedEventHandler ValidarUsuarioConsolaCompleted;
        
        /// <remarks/>
        public event ObtenerParametrosConfiguracionCompletedEventHandler ObtenerParametrosConfiguracionCompleted;
        
        /// <remarks/>
        public event ActualizarParametrosCompletedEventHandler ActualizarParametrosCompleted;
        
        /// <remarks/>
        public event CrearEditarModeradorCompletedEventHandler CrearEditarModeradorCompleted;
        
        /// <remarks/>
        public event ObtenerInfoUsuarioCompletedEventHandler ObtenerInfoUsuarioCompleted;
        
        /// <remarks/>
        public event EliminarModeradorCompletedEventHandler EliminarModeradorCompleted;
        
        /// <remarks/>
        public event CrearEditarSectorCompletedEventHandler CrearEditarSectorCompleted;
        
        /// <remarks/>
        public event ObtenerInfoSectorCompletedEventHandler ObtenerInfoSectorCompleted;
        
        /// <remarks/>
        public event EliminarSectorCompletedEventHandler EliminarSectorCompleted;
        
        /// <remarks/>
        public event CrearEditarCategoriaCompletedEventHandler CrearEditarCategoriaCompleted;
        
        /// <remarks/>
        public event ObtenerInfoCategoriaCompletedEventHandler ObtenerInfoCategoriaCompleted;
        
        /// <remarks/>
        public event EliminarCategoriaCompletedEventHandler EliminarCategoriaCompleted;
        
        /// <remarks/>
        public event GenerarHashCompletedEventHandler GenerarHashCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarUsuarioConsola", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidarUsuarioConsola(string username, string password) {
            object[] results = this.Invoke("ValidarUsuarioConsola", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarUsuarioConsolaAsync(string username, string password) {
            this.ValidarUsuarioConsolaAsync(username, password, null);
        }
        
        /// <remarks/>
        public void ValidarUsuarioConsolaAsync(string username, string password, object userState) {
            if ((this.ValidarUsuarioConsolaOperationCompleted == null)) {
                this.ValidarUsuarioConsolaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarUsuarioConsolaOperationCompleted);
            }
            this.InvokeAsync("ValidarUsuarioConsola", new object[] {
                        username,
                        password}, this.ValidarUsuarioConsolaOperationCompleted, userState);
        }
        
        private void OnValidarUsuarioConsolaOperationCompleted(object arg) {
            if ((this.ValidarUsuarioConsolaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarUsuarioConsolaCompleted(this, new ValidarUsuarioConsolaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerParametrosConfiguracion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] ObtenerParametrosConfiguracion() {
            object[] results = this.Invoke("ObtenerParametrosConfiguracion", new object[0]);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerParametrosConfiguracionAsync() {
            this.ObtenerParametrosConfiguracionAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerParametrosConfiguracionAsync(object userState) {
            if ((this.ObtenerParametrosConfiguracionOperationCompleted == null)) {
                this.ObtenerParametrosConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerParametrosConfiguracionOperationCompleted);
            }
            this.InvokeAsync("ObtenerParametrosConfiguracion", new object[0], this.ObtenerParametrosConfiguracionOperationCompleted, userState);
        }
        
        private void OnObtenerParametrosConfiguracionOperationCompleted(object arg) {
            if ((this.ObtenerParametrosConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerParametrosConfiguracionCompleted(this, new ObtenerParametrosConfiguracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarParametros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarParametros(int[] parametros) {
            object[] results = this.Invoke("ActualizarParametros", new object[] {
                        parametros});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarParametrosAsync(int[] parametros) {
            this.ActualizarParametrosAsync(parametros, null);
        }
        
        /// <remarks/>
        public void ActualizarParametrosAsync(int[] parametros, object userState) {
            if ((this.ActualizarParametrosOperationCompleted == null)) {
                this.ActualizarParametrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarParametrosOperationCompleted);
            }
            this.InvokeAsync("ActualizarParametros", new object[] {
                        parametros}, this.ActualizarParametrosOperationCompleted, userState);
        }
        
        private void OnActualizarParametrosOperationCompleted(object arg) {
            if ((this.ActualizarParametrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarParametrosCompleted(this, new ActualizarParametrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearEditarModerador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CrearEditarModerador(string nick, string email) {
            object[] results = this.Invoke("CrearEditarModerador", new object[] {
                        nick,
                        email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearEditarModeradorAsync(string nick, string email) {
            this.CrearEditarModeradorAsync(nick, email, null);
        }
        
        /// <remarks/>
        public void CrearEditarModeradorAsync(string nick, string email, object userState) {
            if ((this.CrearEditarModeradorOperationCompleted == null)) {
                this.CrearEditarModeradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearEditarModeradorOperationCompleted);
            }
            this.InvokeAsync("CrearEditarModerador", new object[] {
                        nick,
                        email}, this.CrearEditarModeradorOperationCompleted, userState);
        }
        
        private void OnCrearEditarModeradorOperationCompleted(object arg) {
            if ((this.CrearEditarModeradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearEditarModeradorCompleted(this, new CrearEditarModeradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerInfoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerInfoUsuario(string nick) {
            object[] results = this.Invoke("ObtenerInfoUsuario", new object[] {
                        nick});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerInfoUsuarioAsync(string nick) {
            this.ObtenerInfoUsuarioAsync(nick, null);
        }
        
        /// <remarks/>
        public void ObtenerInfoUsuarioAsync(string nick, object userState) {
            if ((this.ObtenerInfoUsuarioOperationCompleted == null)) {
                this.ObtenerInfoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInfoUsuarioOperationCompleted);
            }
            this.InvokeAsync("ObtenerInfoUsuario", new object[] {
                        nick}, this.ObtenerInfoUsuarioOperationCompleted, userState);
        }
        
        private void OnObtenerInfoUsuarioOperationCompleted(object arg) {
            if ((this.ObtenerInfoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInfoUsuarioCompleted(this, new ObtenerInfoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarModerador", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarModerador(string nick) {
            object[] results = this.Invoke("EliminarModerador", new object[] {
                        nick});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarModeradorAsync(string nick) {
            this.EliminarModeradorAsync(nick, null);
        }
        
        /// <remarks/>
        public void EliminarModeradorAsync(string nick, object userState) {
            if ((this.EliminarModeradorOperationCompleted == null)) {
                this.EliminarModeradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarModeradorOperationCompleted);
            }
            this.InvokeAsync("EliminarModerador", new object[] {
                        nick}, this.EliminarModeradorOperationCompleted, userState);
        }
        
        private void OnEliminarModeradorOperationCompleted(object arg) {
            if ((this.EliminarModeradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarModeradorCompleted(this, new EliminarModeradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearEditarSector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CrearEditarSector(string nombre, double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4) {
            object[] results = this.Invoke("CrearEditarSector", new object[] {
                        nombre,
                        x1,
                        y1,
                        x2,
                        y2,
                        x3,
                        y3,
                        x4,
                        y4});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearEditarSectorAsync(string nombre, double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4) {
            this.CrearEditarSectorAsync(nombre, x1, y1, x2, y2, x3, y3, x4, y4, null);
        }
        
        /// <remarks/>
        public void CrearEditarSectorAsync(string nombre, double x1, double y1, double x2, double y2, double x3, double y3, double x4, double y4, object userState) {
            if ((this.CrearEditarSectorOperationCompleted == null)) {
                this.CrearEditarSectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearEditarSectorOperationCompleted);
            }
            this.InvokeAsync("CrearEditarSector", new object[] {
                        nombre,
                        x1,
                        y1,
                        x2,
                        y2,
                        x3,
                        y3,
                        x4,
                        y4}, this.CrearEditarSectorOperationCompleted, userState);
        }
        
        private void OnCrearEditarSectorOperationCompleted(object arg) {
            if ((this.CrearEditarSectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearEditarSectorCompleted(this, new CrearEditarSectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerInfoSector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerInfoSector(string nombre) {
            object[] results = this.Invoke("ObtenerInfoSector", new object[] {
                        nombre});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerInfoSectorAsync(string nombre) {
            this.ObtenerInfoSectorAsync(nombre, null);
        }
        
        /// <remarks/>
        public void ObtenerInfoSectorAsync(string nombre, object userState) {
            if ((this.ObtenerInfoSectorOperationCompleted == null)) {
                this.ObtenerInfoSectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInfoSectorOperationCompleted);
            }
            this.InvokeAsync("ObtenerInfoSector", new object[] {
                        nombre}, this.ObtenerInfoSectorOperationCompleted, userState);
        }
        
        private void OnObtenerInfoSectorOperationCompleted(object arg) {
            if ((this.ObtenerInfoSectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInfoSectorCompleted(this, new ObtenerInfoSectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarSector", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarSector(string nombre) {
            object[] results = this.Invoke("EliminarSector", new object[] {
                        nombre});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarSectorAsync(string nombre) {
            this.EliminarSectorAsync(nombre, null);
        }
        
        /// <remarks/>
        public void EliminarSectorAsync(string nombre, object userState) {
            if ((this.EliminarSectorOperationCompleted == null)) {
                this.EliminarSectorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarSectorOperationCompleted);
            }
            this.InvokeAsync("EliminarSector", new object[] {
                        nombre}, this.EliminarSectorOperationCompleted, userState);
        }
        
        private void OnEliminarSectorOperationCompleted(object arg) {
            if ((this.EliminarSectorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarSectorCompleted(this, new EliminarSectorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CrearEditarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CrearEditarCategoria(string nombre, string nombreedit) {
            object[] results = this.Invoke("CrearEditarCategoria", new object[] {
                        nombre,
                        nombreedit});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CrearEditarCategoriaAsync(string nombre, string nombreedit) {
            this.CrearEditarCategoriaAsync(nombre, nombreedit, null);
        }
        
        /// <remarks/>
        public void CrearEditarCategoriaAsync(string nombre, string nombreedit, object userState) {
            if ((this.CrearEditarCategoriaOperationCompleted == null)) {
                this.CrearEditarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearEditarCategoriaOperationCompleted);
            }
            this.InvokeAsync("CrearEditarCategoria", new object[] {
                        nombre,
                        nombreedit}, this.CrearEditarCategoriaOperationCompleted, userState);
        }
        
        private void OnCrearEditarCategoriaOperationCompleted(object arg) {
            if ((this.CrearEditarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearEditarCategoriaCompleted(this, new CrearEditarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerInfoCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ObtenerInfoCategoria(string nombre) {
            object[] results = this.Invoke("ObtenerInfoCategoria", new object[] {
                        nombre});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerInfoCategoriaAsync(string nombre) {
            this.ObtenerInfoCategoriaAsync(nombre, null);
        }
        
        /// <remarks/>
        public void ObtenerInfoCategoriaAsync(string nombre, object userState) {
            if ((this.ObtenerInfoCategoriaOperationCompleted == null)) {
                this.ObtenerInfoCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInfoCategoriaOperationCompleted);
            }
            this.InvokeAsync("ObtenerInfoCategoria", new object[] {
                        nombre}, this.ObtenerInfoCategoriaOperationCompleted, userState);
        }
        
        private void OnObtenerInfoCategoriaOperationCompleted(object arg) {
            if ((this.ObtenerInfoCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInfoCategoriaCompleted(this, new ObtenerInfoCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarCategoria(string nombre) {
            object[] results = this.Invoke("EliminarCategoria", new object[] {
                        nombre});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarCategoriaAsync(string nombre) {
            this.EliminarCategoriaAsync(nombre, null);
        }
        
        /// <remarks/>
        public void EliminarCategoriaAsync(string nombre, object userState) {
            if ((this.EliminarCategoriaOperationCompleted == null)) {
                this.EliminarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCategoriaOperationCompleted);
            }
            this.InvokeAsync("EliminarCategoria", new object[] {
                        nombre}, this.EliminarCategoriaOperationCompleted, userState);
        }
        
        private void OnEliminarCategoriaOperationCompleted(object arg) {
            if ((this.EliminarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCategoriaCompleted(this, new EliminarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarHash", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerarHash(string text) {
            object[] results = this.Invoke("GenerarHash", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarHashAsync(string text) {
            this.GenerarHashAsync(text, null);
        }
        
        /// <remarks/>
        public void GenerarHashAsync(string text, object userState) {
            if ((this.GenerarHashOperationCompleted == null)) {
                this.GenerarHashOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarHashOperationCompleted);
            }
            this.InvokeAsync("GenerarHash", new object[] {
                        text}, this.GenerarHashOperationCompleted, userState);
        }
        
        private void OnGenerarHashOperationCompleted(object arg) {
            if ((this.GenerarHashCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarHashCompleted(this, new GenerarHashCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ValidarUsuarioConsolaCompletedEventHandler(object sender, ValidarUsuarioConsolaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarUsuarioConsolaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarUsuarioConsolaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerParametrosConfiguracionCompletedEventHandler(object sender, ObtenerParametrosConfiguracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerParametrosConfiguracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerParametrosConfiguracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ActualizarParametrosCompletedEventHandler(object sender, ActualizarParametrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarParametrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarParametrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CrearEditarModeradorCompletedEventHandler(object sender, CrearEditarModeradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearEditarModeradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearEditarModeradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerInfoUsuarioCompletedEventHandler(object sender, ObtenerInfoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInfoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerInfoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void EliminarModeradorCompletedEventHandler(object sender, EliminarModeradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarModeradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarModeradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CrearEditarSectorCompletedEventHandler(object sender, CrearEditarSectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearEditarSectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearEditarSectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerInfoSectorCompletedEventHandler(object sender, ObtenerInfoSectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInfoSectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerInfoSectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void EliminarSectorCompletedEventHandler(object sender, EliminarSectorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarSectorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarSectorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CrearEditarCategoriaCompletedEventHandler(object sender, CrearEditarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearEditarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearEditarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ObtenerInfoCategoriaCompletedEventHandler(object sender, ObtenerInfoCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInfoCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerInfoCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void EliminarCategoriaCompletedEventHandler(object sender, EliminarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GenerarHashCompletedEventHandler(object sender, GenerarHashCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarHashCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarHashCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591